version: '2'

services:
  web-dev:
    build:
      context: .
    environment:
      NODE_ENV: development
    volumes:
    - "./:/todo-list/"
    ports:
      - "3000:3000"
    links:
    - "db-dev"

  db-dev:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo-dev
    ports:
      - "5432:5432"