version: '2'

services:
  web:
    build: .
    volumes:
    - "./src:/todo-list/src"
    ports:
      - "3000:3000"
    links:
    - "db"

  db:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo-dev
    ports:
      - "5432:5432"