version: '2'

services:
  web-test:
    build: .
    environment:
      NODE_ENV: test
    volumes:
    - "./:/todo-list/"
    ports:
    - "3000:3000"
    links:
    - "db-test"

  db-test:
    image: postgres:10
    environment:
    - POSTGRES_PASSWORD=password
    - POSTGRES_USER=postgres
    - POSTGRES_DB=todo-test
    ports:
    - "5432:5432"
